const fortunes = [
    "Today is going to be a great day!",
    "Success comes to those who are patient.",
    "New opportunities are on your doorstep.",
    "A smile is the best medicine.",
    "Help someone today and it will come back to you tomorrow.",
    "Every challenge is a new beginning.",
    "Believing is half the battle.",
    "Take time for yourself today.",
    "Learn something new every day.",
    "The road to success is paved with perseverance.",
    "Your hard work will soon pay off.",
    "Happiness is a journey, not a destination.",
    "Trust your instincts.",
    "An unexpected event will soon bring you joy.",
    "Embrace change and new experiences.",
    "You are capable of amazing things.",
    "Kindness is the greatest wisdom.",
    "Your positive attitude will inspire others.",
    "The best is yet to come.",
    "Your creativity will lead you to success.",
    "You will find the strength to overcome any obstacle.",
    "Cherish the small moments in life.",
    "Adventure is around the corner.",
    "You are exactly where you need to be.",
    "Your dreams are within reach.",
    "A new friendship will bring you happiness.",
    "Take a chance and you won't regret it.",
    "Good things take time.",
    "Your perseverance will be rewarded.",
    "A fresh start will bring you new opportunities.",
    "Believe in the magic of new beginnings.",
    "Your kindness will come back to you.",
    "The harder you work, the luckier you get.",
    "A positive mindset brings positive things.",
    "You have the power to change your life.",
    "Your efforts are paying off.",
    "Stay patient and trust your journey.",
    "The future is bright and full of promise.",
    "Your energy is contagious.",
    "Keep moving forward, success is near.",
    "A new adventure awaits you.",
    "You are stronger than you think.",
    "Every day is a new opportunity.",
    "You are a light to those around you.",
    "Great things never come from comfort zones.",
    "Believe in yourself and all that you are.",
    "Your happiness is in your hands.",
    "New doors are opening for you.",
    "You are a magnet for positive energy.",
    "Your potential is limitless.",
    "You are destined for greatness.",
    "Expect the unexpected.",
    "Not every day will be a good day.",
    "You might face a difficult challenge soon.",
    "Prepare for a disappointment.",
    "Things may not go as planned.",
    "You will encounter an obstacle in your path.",
    "Someone might let you down.",
    "Beware of false friends.",
    "A setback is on the horizon.",
    "You might have to rethink your plans.",
    "Troubles never come alone.",
    "A tough decision awaits you.",
    "Don't count your chickens before they hatch.",
    "You may face criticism.",
    "An old problem may resurface.",
    "Not everything is as it seems.",
    "Beware of miscommunication.",
    "A surprise may not be a pleasant one.",
    "Expect some delays.",
    "Not everyone has your best interests at heart.",
    "You may lose something valuable.",
    "Be prepared for a letdown.",
    "Disappointment is a part of life.",
    "You might face a financial challenge.",
    "A relationship may face a rough patch.",
    "Beware of taking unnecessary risks.",
    "An error may cause you trouble.",
    "You might need to ask for help.",
    "A misunderstanding could cause issues.",
    "Be cautious in your decisions.",
    "Not all efforts yield results.",
    "You might encounter resistance.",
    "An unexpected expense may arise.",
    "A minor inconvenience could become a major problem.",
    "Someone may try to deceive you.",
    "You might need to compromise.",
    "A challenge may test your patience.",
    "Something you rely on might fail.",
    "A difficult situation may arise.",
    "Beware of overconfidence.",
    "You may have to face a harsh reality.",
    "Not everyone will support your choices.",
    "A promise might be broken.",
    "You may need to rethink your strategy.",
    "A complication may disrupt your plans.",
    "You might face an unexpected hurdle.",
    "A rumor could cause trouble.",
    "Not all news will be good news.",
    "A small mistake could have big consequences.",
    "You might need to deal with conflict."
];


function getNewFortune() {
    const randomIndex = Math.floor(Math.random() * fortunes.length);
    return fortunes[randomIndex];
}

document.getElementById('newFortune').addEventListener('click', () => {
    document.getElementById('fortune').textContent = getNewFortune();
});

// Sayfa yüklendiğinde rastgele bir öneri göster
document.getElementById('fortune').textContent = getNewFortune();
